FROM node:16                                                                                                                                                                                                                                                                                                                                  

WORKDIR /app                                                                                                                                                                                                                                                                                                     

COPY . /app                                                                                                                                                                            

RUN npm install -g cnpm -registry=https://registry.npm.taobao.org \ 
&& cnpm i pm2 -g \                                                                                                                                                                                                                                                                                       
&& cnpm install \                                                                                                                                                                     
&& cnpm run build                                                                                                                                                                                                                                                                                                                                    

EXPOSE 5312                                                                                                                                                                                                                                                                                                                                              

CMD ["pm2-runtime","start","dist/bin/www.js"]   